apiVersion: v1
kind: Service
metadata:
  name: server-strapi
spec:
  ports:
    - nodePort: 32331
      port: 1337
      protocol: TCP
      targetPort: 1337
  selector:
    app: server-strapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-strapi
spec:
  selector:
    matchLabels:
      app: server-strapi
  replicas: 1
  template:
    metadata:
      labels:
        app: server-strapi
      annotations:
        date/deploy-date: {{ now | quote }}
    spec:
      containers:
        - name: server-strapi
          image: {{ .Values.server_strapi.image }}:{{ .Values.server_strapi.tag }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_HOST
              value: {{ .Values.server_strapi.database_host }}
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: {{ .Values.server_strapi.database_name }}
            - name: DATABASE_USERNAME
              value: {{ .Values.server_strapi.database_username }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.server_strapi.database_password }}
          ports:
            - containerPort: 1337
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 1337
            initialDelaySeconds: 3
            periodSeconds: 3

